---
extends: default

ignore: |
  *.j2
  kubeconfig-*.yaml
  .github/

rules:
  line-length:
    max: 160
    level: warning
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
