[rpis]
portainer-pi ansible_host=10.0.3.2 ansible_user=pancakes
k3s-edge-node-1 ansible_host=10.0.3.3 ansible_user=pancakes
k3s-edge-node-2 ansible_host=10.0.3.4 ansible_user=pancakes
k3s-edge-node-3 ansible_host=10.0.3.5 ansible_user=pancakes
codeserver-pi ansible_host=10.0.3.15 ansible_user=pancakes

[portainer]
portainer-pi

[codeserver]
codeserver-pi

[k3s-edge]
k3s-edge-node-1
k3s-edge-node-2
k3s-edge-node-3

[proxmox]
proxmox-node-1 ansible_host=10.0.3.6 ansible_user=root

[rke2-mgmt]
rke2-mgmt-node-1 ansible_host=10.0.3.41 ansible_user=ubuntu
rke2-mgmt-node-2 ansible_host=10.0.3.42 ansible_user=ubuntu
rke2-mgmt-node-3 ansible_host=10.0.3.43 ansible_user=ubuntu
